# Lab 4: Q-table based reinforcement learning



Solve [`FrozenLake8x8-v1`](https://www.gymlibrary.dev/environments/toy_text/frozen_lake/) using a Q-table.


1. Import Necessary Packages (e.g. `gym`, `numpy`):

In [68]:
import pygame
import numpy as np
import gym
import time
import random
from IPython.display import clear_output
pygame.init()

(5, 0)


2. Instantiate the Environment and Agent

In [69]:
environment = gym.make("FrozenLake8x8-v1")#render_mode='human'
environment.reset()


(0, {'prob': 1})

3. Set up the QTable:

In [70]:
actions = environment.action_space.n
states = environment.observation_space.n
q_table = np.zeros((states, actions))
print(q_table)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


4. The Q-Learning algorithm training

In [72]:
episodes = 10000 #Total amount of episodes
max_steps = 100 #Max steps per episode
learning_rate = 0.1  #Learning rate
randomness = 1.0 #Exploratoion rate
max_randomness = 1.0 #Exploration propability at start
min_randomness = 0.01 #Min exploration
zombie_rate = 0.001 #Decay rate
gamma = 0.9 #Discounting rate 
rewards = []

for episode in range(episodes):
    state = environment.reset()[0] #Resets and collects the first state in the env
    finished = False
    all_rewards = 0
    moves = 0
    if episode % 200 == 0:#Saves every 200th  
        np.savetxt("Q_Table", q_table)
    random_value = random.random()
    for moves in range(max_steps):
        #random_value = random.random()
        #If its greather than randomness, then we're taking the biggest Q value
        if random_value > randomness:
            action = np.argmax(q_table[state, :]) #Finds the highest Qvalue which matches the state we have. 
        #If its not, then we're doing a random choice
        else: 
            action = environment.action_space.sample()
        #Does the action    
        new_state, reward, finished, _ , _ = environment.step(action)
        #Updating our Qtable 
        q_table[state,action] = q_table[state, action] + learning_rate * (reward + gamma * np.max(q_table[new_state, :]) - q_table[state, action])
        all_rewards += reward
        state = new_state #Update our current state
        if finished:
            break 
    #We're reducing randomness, as we need less exploration over time   
    randomness = min_randomness + (max_randomness - min_randomness) * np.exp(- zombie_rate * episode)
    rewards.append(all_rewards)
print(q_table)
print(np.average(new_state))


[[8.82035770e-04 9.06889640e-04 2.34150506e-03 1.02062296e-03]
 [1.18197249e-03 1.17353393e-03 2.54318888e-03 1.40086166e-03]
 [1.69532783e-03 1.70096880e-03 3.55864767e-03 1.82774410e-03]
 [2.60115528e-03 3.25747410e-03 5.42714017e-03 2.61491865e-03]
 [4.15871334e-03 4.91554730e-03 7.53403397e-03 4.13146553e-03]
 [6.22801129e-03 6.90186016e-03 1.00259097e-02 6.22512885e-03]
 [8.17537171e-03 6.55918899e-03 1.23445419e-02 5.69833791e-03]
 [8.51691402e-03 1.34909315e-02 8.54695543e-03 8.50685921e-03]
 [8.72562443e-04 8.69668860e-04 8.73947608e-04 1.95169820e-03]
 [1.13229455e-03 1.13939312e-03 1.09463644e-03 2.38123919e-03]
 [1.42275047e-03 1.37608273e-03 1.46968589e-03 3.37395328e-03]
 [1.28828421e-03 2.00027605e-03 1.93695841e-03 4.71261252e-03]
 [2.62644646e-03 2.79639438e-03 3.49213629e-03 7.13024845e-03]
 [2.33382835e-03 3.74314675e-03 5.48977725e-03 1.04364265e-02]
 [8.35205126e-03 7.83914022e-03 1.73079395e-02 5.91822571e-03]
 [1.03570732e-02 8.78482798e-03 1.93941291e-02 8.795244

5. Evaluate how well your agent performs
* Render output of one episode
* Give an average episode return

In [73]:
environment = gym.make("FrozenLake8x8-v1", render_mode='human')
environment.reset()

(0, {'prob': 1})

In [74]:
for episode in range(1):
    state = environment.reset()[0]
    finished = False
    moves = 0
    for moves in range(max_steps):
        action = np.argmax(q_table[state, :])
        new_state, reward, finished, _ , _ = environment.step(action)
        if finished:
            #If its done with an episode, it will render the output
            environment.render()
            print("Number of steps", moves)
            break
        state = new_state
environment.close()
#Average episode return
print(np.average(new_state))

Number of steps 25
35.0


6. (<i>Optional</i>) Adapt code for one of the continuous [Classical Control](https://www.gymlibrary.dev/environments/classic_control/) problems. Think/talk about how you could use our  `Model` class from last Thursday to decide actions.